name: justcleandrycleaner
description: A new Just Clean Drycleaner

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.2
  webview_flutter: ^2.8.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  
  flutter_lints: ^2.0.0
  # flutter_webview_plugin: ^0.4.0

flutter:
  
  
  uses-material-design: true
  
  assets:
     - assets/icon.png
